# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


## source .profile if exists
[[ -e ~/.profile ]] && emulate sh -c 'source ~/.profile'


export GITHUB_USERNAME="TanakritBenz" # https://help.github.com/articles/remembering-your-github-username-or-email

## Bug fix: Tab and window title not updated after logging out of SSH remote session
# xterm titlebar
TITLEBAR=$(printf '\033]0;')
BELL=$(printf '\007')
# set prompt
case $TERM in
    # xterm and variants, set the titlebar 
    xterm*) PS1='${TITLEBAR}[\u@\h]${BELL}\h \$ ' ;;                                                                    

    # anything else, don't try to set the titlebar
    *) PS1='\u@\h \$ ' ;;                                                                                         
esac


export PATH=$HOME/bin:$PATH
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:/opt/homebrew/bin:/usr/local/bin


## Go Lang
export GOPATH=$HOME/go
export GOROOT="$(brew --prefix golang)/libexec"
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

## Flutter
export PATH=$PATH:$HOME/flutter/bin

## Initialize rbenv
eval "$(rbenv init -)"


## Initialize nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export NODE_PATH=`which node`


## iterm2 shell integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


####
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000000 # Setting history to 1 million commands
SAVEHIST=1000000
#### End of lines configured by zsh-newuser-install


####
# The following lines were added by compinstall
zstyle :compinstall filename "$HOME/.zshrc"
autoload -Uz compinit
compinit
#### End of lines added by compinstall


## Sublime Text
export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"


## Show hidden files ##
alias l.='ls -d .*'

## A quick way to get out of current directory ##
alias ..='cd ..'
alias .2='cd ../../'
alias .3='cd ../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../../'

## Colorize the grep command output for ease of use (good for log files)##
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

## Ports
check_port() {
  if [ -n "$1" ]; then
    lsof -n -i :$1 | grep LISTEN
  fi
}
kill_port() {
    echo "Checking port $1"
    pid=$(lsof -t -i :"$1" -sTCP:LISTEN)

    if [ -z "$pid" ]
    then
        echo "Already open"
    else
        echo "Killing $pid"
        kill -9 $pid
    fi
}
nuke_ports() {
    for i in $(seq $1 $2); do kill_port $i; done
}

## Get top process eating memory
alias psmem='ps aux | sort -nr -k 4'
alias psmem10='ps aux | sort -nr -k 4 | head -10'

## Get top process eating cpu ##
alias pscpu='ps aux | sort -nr -k 3'
alias pscpu10='ps aux | sort -nr -k 3 | head -10'

alias cat="bat --theme=\$(defaults read -globalDomain AppleInterfaceStyle &> /dev/null && echo default || echo GitHub)"
alias diff='colordiff' # Dont forget to "brew install colordiff"
alias df='df -H'
alias du='du -ch'
alias c="clear"
alias j='jobs -l'
alias vi="nvim"
alias vim="nvim"
alias bsl="brew services list"
alias g='git'
alias gws='git status --short'
alias gwS='git status'
alias gdif='git diff'
alias ga='git add'
alias gA='git add .'
alias gbc='git checkout -b'
alias gcm='git commit --message'
alias grm='git pull --rebase origin master'
alias grc="git rebase --continue"
function git_current_branch() {
  git branch 2> /dev/null | sed -n -e 's/^\* \(.*\)/[\1]/p' | sed 's/[][]//g'
};
function current_branch() {
  git_current_branch
};
function g_last_hash() {
  git rev-parse --short HEAD
};
function gp() {
  git push origin "$(current_branch)";
};
function gpF() {
  git push -f origin "$(current_branch)";
};
function gpU() {
  git push --set-upstream origin "$(current_branch)";
  git push -u origin "$(current_branch)";
};
function g_squash () {
  if [ -n "$1" ]; then
    git reset --soft HEAD~$1 && git commit --edit -m"$(git log --format=%B --reverse HEAD..HEAD@{1})"
  fi
};


###########################################
##            Instacart stuff            ##
###########################################
cdapp() {
  cd ~/bento-remote-carrot
  cd `find . -name .isc|rev|cut -d/ -f 2-|rev|grep "$1\$"`
}
kill_v3() { ## Kill v3 rails server
  lsof -n -i :3000 | grep -E 'ruby.*LISTEN' | awk '{print $2}' | xargs kill -9
}
kill_v4() { ## Kill v4 rails server
  lsof -n -i :3030 | grep -E 'ruby.*LISTEN' | awk '{print $2}' | xargs kill -9
}
alias carrot="cd ~/bento-remote-carrot"
alias instacart="cd ~/bento-remote-carrot/customers/instacart"
alias store="cd ~/bento-remote-carrot/customers/store"
alias landing="cd ~/bento-remote-carrot/customers/landing"
alias adsbackend="cd ~/bento-remote-carrot/ads/ads-backend"
alias migrations="~/bento-remote-carrot/tools/migrations"
alias v3="cd ~/bento-remote-carrot/customers/instacart"
alias v4="cd ~/bento-remote-carrot/customers/customers-backend"
alias customers-backend="cd ~/bento-remote-carrot/customers/customers-backend"
alias v3serv="rbenv rehash && bundle exec rails s -p 3000"
alias v4serv="rbenv rehash && REQUIRED_ENGINES=graph bundle exec rails s -p 3030"
alias cons="rbenv rehash && bundle exec rails c"
alias hubc="rbenv rehash && bundle exec rake hub:combined"
alias hube="rbenv rehash && bundle exec rake hub:endpoint"
alias adsrpc="rbenv rehash && bundle exec bin/rpc"
alias wker="forego start -c all=1,webpack=0,web=0"


### BEGIN--Instacart Shell Settings. (Updated: Thu Feb  9 22:43:22 EST 2023. [Script Version 1.3.23])
# This Line Added Automatically by Instacart Setup Script
# The sourced file contains all of the instacart utilities and shell settings
# To remove this functionality, leave the block, and enter "NO-TOUCH" in the BEGIN line, and comment the line below:
source /Users/benzsupanaraphan/.instacart_shell_profile
### END--Instacart Shell Settings.


### BENTO_COMPLETIONS_START
export BENTO_COMPLETIONS_VERSION=2
autoload -U compinit; compinit
source <(bento completion zsh --silent)
export PGHOST=localhost # Set PGHOST to talk to bento postgres
### BENTO_COMPLETIONS_END
